---
- name: Copy SLURM systemd service 
  command: 
   cp /tmp/slurm-{{ slurm_version }}/etc/slurmd.service /lib/systemd/system/  

- name: Reload systemd config 
  systemd: 
    daemon_reload: yes

- name: Reload systemd service 
  systemd:
    state: restarted
    daemon_reload: yes
    name: slurmd

- name: Copy slurm.conf 
  template:
   src: slurm.conf.j2
   dest: /opt/slurm-{{ slurm_version }}/etc/slurm.conf
  notify: 
    - Restart Slurmd 
