---

- name: Copy SLURM slurmctld systemd service 
  command: 
   cp /tmp/slurm-{{ slurm_version }}/etc/slurmctld.service /lib/systemd/system/

- name: Copy SLURM slurmdbd systemd service 
  command: 
    cp /tmp/slurm-{{ slurm_version }}/etc/slurmdbd.service /lib/systemd/system/

- name: Reload systemd config 
  systemd: 
    daemon_reload: yes

## Create Slurm partition information with slurm manager 


## See what else needs to be created 

- name: Copy slurm.conf 
  template:
   src: slurm.conf.j2
   dest: /opt/slurm-{{ slurm_version }}/etc/slurm.conf
  notify: 
    - Restart Slurmctld 
    - Restart Slurmdbd

- name: Ensure slurmd is not running in front node
  shell: pgrep slurmd && killall slurmd
  ignore_errors: yes

- name: Wait Slurm daemon to be up
  wait_for:
    port: 6817

- name: Reconfigure SLURM
  become: true
  become_user: slurm
  command: scontrol reconfigure






