---

- name: Copy SLURM slurmctld systemd service 
  command: 
   cp /tmp/slurm-{{ slurm_version }}/etc/slurmctld.service /lib/systemd/system/

- name: Reload systemd config 
  systemd: 
    daemon_reload: yes

- name: Reload systemd service 
  systemd:
    state: restarted
    daemon_reload: yes
    name: slurmctld

- name: Copy SLURM slurmdbd systemd service 
  command: 
    cp /tmp/slurm-{{ slurm_version }}/etc/slurmdbd.service /lib/systemd/system/

- name: Reload systemd config 
  systemd: 
    daemon_reload: yes

- name: Reload systemd service 
  systemd:
    state: restarted
    daemon_reload: yes
    name: slurmdbd

