---

# Installation and Configuration of SLURM
- name: Set SLURM version
  set_fact:
    SLURM_VERSION: "{{ slurm_version }}"

- name: Update package cache
  apt: 
    update_cache: yes
    cache_valid_time: 2400

- name: Install SLURM Dependencies
  apt: 
   name: "{{ packages }}"
  vars: 
   packages: 
   - gcc
   - libpq5
   - libmunge-dev
   - libmunge2
   - munge 
   - bzip2
   - make

- name: Pull source from git
  git: 
   repo: 'git://github.com/SchedMD/slurm.git'
   dest: /tmp/slurm-{{ slurm_version }}
   version: slurm-{{ slurm_version }}

- name: Configure SLURM
  command: "{{ item }} chdir=/tmp/slurm-{{ slurm_version }}" 
  with_items: 
  - ./configure --prefix={{ slurm_path }} --sysconfdir={{ slurm_path }}/etc --enable-debug

- name: Build the SLURM target
  make:
   chdir: /tmp/slurm-{{ slurm_version }}
   params:
      NUM_THREADS: 2

- name: Run the 'make install' against target
  make: 
   chdir: /tmp/slurm-{{ slurm_version }}
   target: install 
  become: yes

- name: Add bin/sbin directories to system-wide $PATH.
  copy:
   dest: /etc/profile.d/slurm.sh
   content: 'PATH=$PATH:{{ slurm_bin_path }}'

# Confirmation that munge is running.
- name: Start Munge Service
  service: 
   name: munge
   state: started
  register: munge_installed
  ignore_errors: yes
  
- stat: path=/etc/munge/munge.key
  register: munge_key

- fail: 
    msg: "File is not owned by munge"
  when: munge_key.stat.pw_name != 'munge'

- name: Set SLURM conf file path as fact
  set_fact:
    SLURM_CONF: "/opt/slurm-{{ slurm_version }}/etc/slurm.conf"
    SLURM_DAEMON: "slurmd"
    SLURM_SERVICE: "slurmctld"

# SLURM User/Group Creation.
- name: Create SLURM Group
  group: 
    name: "{{ slurm_group }}"
    gid: "{{ slurm_uid }}"
    system: yes
    state: present

- name: Create SLURM User 
  user: 
    name: "{{ slurm_user }}"
    uid: "{{ slurm_gid }}"
    shell: /bin/bash 
    system: yes 
    group: "{{ slurm_user }}"

# Folder Creation for SLURM to function.
- name: Create folders and user permissions
  file: 
   path: "{{item}}"
   state: directory
   owner: "{{ slurm_user }}"
   group: "{{ slurm_group }}"
  with_items:
    - /var/spool/slurm
    - /var/log/slurm
    - /var/slurm/checkpoint
    - /opt/slurm-{{ slurm_version }}

# Copy the slurm.conf to all slurm nodes. 
- name: Copy slurm.conf 
  template:
   src: slurm.conf.j2
   dest: /opt/slurm-{{ slurm_version }}/etc/slurm.conf

- include: controller.yml
  when: slurm_enable.controller | default(false) | bool

- include: compute.yml
  when: slurm_enable.compute| default(false) | bool

- include: headnode.yml
  when: slurm_enable.headnode| default(false) | bool